version: '3.8'

services:
  # Боевая бд (порт 5432)
  prod_db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secretpassword
      POSTGRES_DB: prod_database
    ports:
      - "5432:5432"
    volumes:
      # Скрипт для инициализации
      - ./init_prod.sql:/docker-entrypoint-initdb.d/init.sql

  # Тестовая бд (порт 5433)
  test_db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secretpassword
      POSTGRES_DB: test_database
    ports:
      - "5433:5432"
    volumes:
      # Скрипт для инициализации
      - ./init_test.sql:/docker-entrypoint-initdb.d/init.sql